-
  name: Script Moduile Example
  hosts: all
  become: yes
  tasks: 
  - name: Run a script
    script: ./install-space-invaders.sh
    register: script_output

  - name: Show output
    debug:
      var: script_output.stdout
